# Generated by Django 2.2.5 on 2020-12-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientID', models.IntegerField(blank=True, null=True)),
                ('PatientEncounterID', models.CharField(blank=True, max_length=100, null=True)),
                ('InpatientNoteTypeDSC', models.TextField(blank=True, null=True)),
                ('ContactDTS', models.DateField(blank=True, null=True)),
                ('EncounterTypeDSC', models.TextField(blank=True, null=True)),
                ('NoteID', models.IntegerField(blank=True, null=True)),
                ('LocalNoteID', models.IntegerField(blank=True, null=True)),
                ('NoteTXT', models.TextField(blank=True, null=True)),
                ('ProviderNM', models.TextField(blank=True, null=True)),
                ('PrimaryDepartmentDSC', models.TextField(blank=True, null=True)),
                ('CurrentPCP', models.TextField(blank=True, null=True)),
                ('Year', models.CharField(blank=True, max_length=4, null=True)),
                ('KeywordCount', models.IntegerField(blank=True, null=True)),
                ('Label', models.TextField(choices=[('0', 'No Relevant Information'), ('1', 'Relevant to Cognitive Concern')], default='Incomplete')),
                ('Annotator', models.TextField(blank=True, null=True)),
                ('DateAnnotated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientDemographic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientID', models.IntegerField(blank=True, null=True)),
                ('BirthDTS', models.DateField(blank=True, null=True)),
                ('EthnicGroupDSC', models.TextField(blank=True, null=True)),
                ('MaritalStatusDSC', models.TextField(blank=True, null=True)),
                ('SexDSC', models.TextField(blank=True, null=True)),
                ('Assigned', models.BooleanField(default=False)),
                ('SyndromicDiagnosis', models.TextField(choices=[('0', 'No Cognitive Concern'), ('1', 'Mild Cognitive Impairment'), ('2', 'Dementia')], default='Incomplete')),
                ('DementiaSeverity', models.TextField(choices=[('0', 'None'), ('1', 'Mild'), ('2', 'Moderate'), ('3', 'Severe'), ('9', 'Unknown')], default='Incomplete')),
                ('LabelCertainty', models.TextField(choices=[('0', 'Not Confident'), ('1', 'Mildly Confident'), ('2', 'Moderately Confident'), ('3', 'Highly Confident')], default='Incomplete')),
                ('Annotator', models.TextField(blank=True, null=True)),
                ('DateAnnotated', models.DateTimeField(blank=True, null=True)),
                ('Scratchpad', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientID', models.IntegerField(blank=True, null=True)),
                ('Year', models.CharField(blank=True, max_length=4, null=True)),
                ('CurrentMeds', models.TextField(blank=True, null=True)),
                ('MedHistory', models.TextField(blank=True, null=True)),
                ('NoShows', models.IntegerField(blank=True, null=True)),
                ('Cancellations', models.IntegerField(blank=True, null=True)),
                ('NumberNotes', models.IntegerField(blank=True, null=True)),
                ('TotalEncounters', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
