# Generated by Django 3.1.2 on 2021-01-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdemographic',
            name='Consensus',
            field=models.BooleanField(default=False),
        ),
    ]
