# Generated by Django 3.1.2 on 2021-01-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0002_patientdemographic_consensus'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdemographic',
            name='ConsensusActor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
