# Generated by Django 3.1.2 on 2021-01-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_patientdemographic_consensusactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='ProviderTitleDSC',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdemographic',
            name='CoordinationNote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdemographic',
            name='EducationLevelDSC',
            field=models.TextField(blank=True, null=True),
        ),
    ]
