# Generated by Django 3.1.2 on 2021-01-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0004_auto_20210105_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='ImagingInInterval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='LabsInInterval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientdemographic',
            name='PatientImaging',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdemographic',
            name='PatientLabs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientyear',
            name='ICDCodes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
