# Generated by Django 3.1.2 on 2021-01-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0006_auto_20210112_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdemographic',
            name='MRN',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
